services:
  db:
    image: postgres:16
    container_name: estoque_reuso_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: estoque_reuso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: icaro123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d estoque_reuso"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
